# 评论长度限制
reviewLengthLimit: 200

# 明日超能力推送功能（可选）
# enable: 是否启用明日超能力推送功能
# cron: 什么时候进行推送
TomorrowSuperPowerInfo:
  enable: false
  cron: "0 30 23 * * ?"

# 一行一个用户id
# 设置到里面的用户则无法进行评论
blacklist:
  id:
    - 1
    - 4
